name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Code
        run: |
          export PYTHONPATH=src
          python3 src/main.py 

# TODO - (OUTPUT) download summary - step 7 
